# Generated by Django 5.0 on 2024-01-03 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 1, 3, 3, 497137, tzinfo=datetime.timezone.utc)),
        ),
    ]
